---
apiVersion: v1
kind: Service
metadata:
  name: wikijs-svc
  labels:
    component: wikijs
spec:
  selector:
    component: wikijs
  type: ClusterIP
  ports:
    - name: tcp-80
      protocol: TCP
      port: 80
      targetPort: 3000
    - name: tcp-443
      protocol: TCP
      port: 443
      targetPort: 3443
